# Generated by Django 4.2.21 on 2025-05-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('cover', models.URLField()),
                ('publisher', models.CharField(max_length=100)),
                ('customer_review_rank', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
